### ISSUE TITLE
Not catching all comments

### ISSUE THREAD

**Issue by Spootacular** [Spootacular/Mnemosyne-2.0#10]
[This](https://www.reddit.com/r/KotakuInAction/comments/4nxuft/twitter_bullshit_mark_kern_back_suspended_over/) post, it did not catch [this](https://www.reddit.com/r/KotakuInAction/comments/4nxuft/twitter_bullshit_mark_kern_back_suspended_over/d47vaz0) comment

May just be too low of a request limit. Reddit API seems to support requesting all things newer than a specified ID but when I was looking through RedditSharp I didn't see this implemented. If that sounds like a better solution I can look into adding it in.

**Comment by chuggafan** [comment]
if you can add it in later i'd love it, make a fork of redditsharp and we'll use it

**Comment by chuggafan** [comment]
Error found, remember that commit you made to "fix" the stuff? guess what, that broke it instead, i can't figure out for my life how to revert to there though

**Comment by Spootacular** [comment]
The two checks should be necessary, as the bot should not be editing or commenting if either of those lists are empty; it will have nothing to work with if they were. What is broke? IIRC I did move [this](https://github.com/Spootacular/Mnemosyne-2.0/blob/master/Mnemosyne%20Of%20Mine/Program.cs#L155) line and now that I'm looking back over it, *that* was a mistake and it will repeatedly check comments with no links.
