### ISSUE TITLE
Everything broke

### ISSUE THREAD

**Issue by chuggafan** [Spootacular/Mnemosyne-2.0#12]
I can't find the last working commit, it's late for me, and i have to be somewhere all day tomorrow, could you find the last working commit? like the one before the one where you asked for a pull? it's late for me and i have to get up massively early

**Comment by Spootacular** [comment]
Might be one of the few times 'rewriting history' is a good idea there, I'd say hard reset to 55db574 and force push it. Shouldn't hurt anything in this instance.

**Comment by chuggafan** [comment]
Fixed, + won't give out empty comments, reason unkown, not touching that code ever again to not break it lol

**Comment by Spootacular** [comment]
Well that line I pointed to that I had moved in the other issue wasn't even the one I meant either, the one above would make it recheck comments repeatedly with where I put it. Haven't been able to concentrate these past two days but I do see it's running right now so that's good

**Comment by chuggafan** [comment]
It needs periodic rebooting, but that's OAuth's fault, so
